### ISSUE TITLE
Error in TAB Trade Recent Table

### ISSUE THREAD

**Issue by SkyBadPT** [cp6/DayZ-Trader-Bank-logging#1]
I have the following error in tab "Trade Recent Table":

`Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''500'' at line 1 in C:\DayZTraderLog\class.php:240 Stack trace: #0 C:\DayZTraderLog\class.php(240): PDOStatement->execute(Array) #1 C:\DayZTraderLog\trades_table.php(22): dzTraderBankLogging->recentTradeTable(24, 500) #2 {main} thrown in C:\DayZTraderLog\class.php on line 240`

**Comment by cp6** [comment]
See if https://github.com/cp6/DayZ-Trader-Bank-logging/commit/5e6328a4f5db6fd3f372fef3c821bdb2e1379c9d fixed?

**Comment by cp6** [comment]
Ensure that only int values (numbers) are passed into `recentTradeTable(24, 500)`

Not strings `recentTradeTable(24, '500')`

**Comment by SkyBadPT** [comment]
Yes, it's fixed!

**Comment by SkyBadPT** [comment]
By default it's recentTradeTable(int $hours = 12, int $limit = 400) so only ints are passing
