### ISSUE TITLE
Only 1item inserts everytime

### ISSUE THREAD

**Issue by PB-Lesco** [cp6/DayZ-Trader-Bank-logging#3]
the site cant find my File

**Comment by Pakev** [comment]
C:\Users\Administrator\Desktop\DayZ Server\servers\LIVE\profiles\Trader\TBlogs\trade_2020-06-11.log NOT FOUND

C:\Users\Administrator\Desktop\DayZ Server\servers\LIVE\profiles\Trader\TBlogs\atm_2020-06-11.log NOT FOUND

**Comment by PB-Lesco** [comment]
Okay Fixed for now but got other Problems running in -.-


![image](https://user-images.githubusercontent.com/22914346/84444959-329a9800-ac43-11ea-800b-194fb98c4bd3.png)

**Comment by cp6** [comment]
I need more information. What do your log files look like?

**Comment by PB-Lesco** [comment]
![image](https://user-images.githubusercontent.com/22914346/84497517-3cf27b80-acaf-11ea-82b8-a366b71e8e8e.png)

**Comment by PB-Lesco** [comment]
![image](https://user-images.githubusercontent.com/22914346/84516597-4e974b80-acce-11ea-815c-c093394f2384.png)


![image](https://user-images.githubusercontent.com/22914346/84516619-5656f000-acce-11ea-80bb-3cdd437409cd.png)
